Update base image to eclipse-temurin:21-jdk
octopusden/octopus-release-management-service pull request #16
Opened 2024-10-16 10:20 UTC by qu0d

2024-10-16 10:27 UTC, CamaradeRoman submitted a review, later dismissed

2024-10-16 13:11 UTC, ozonophore submitted a review, later dismissed

2024-10-21 15:19 UTC, aryabokon requested changes
обновляем код до компиляции на Java21

2024-10-23 16:48 UTC, qu0d commented
@aryabokon 
обновил код до компиляции на Java21
на QA запросы прошли

2024-10-24 12:01 UTC, aryabokon approved these changes

2024-10-24 14:55 UTC, aryabokon approved these changes

2024-10-25 12:02 UTC, pgorbachev approved these changes

2024-10-25 12:03 UTC, merged